version: "3.9"
services:
  pg:
    image: postgres
    container_name: pg
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
  
  app:
    build: .
    depends_on:
      - pg
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
    networks:
      - app_network
volumes:
  pgdata:
    driver: local
  
networks:
  app_network:
    driver: bridge